### ISSUE TITLE
[FEAT] Support for non-Alsa systems

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/skill-audio_record#26]
### Objective

I'd like to use this skill on my Mac. 🙂 

### Initial Implementation Requirements

Make `aplay` a configurable option instead of hardcoded. `afplay` is the default on Mac.

**Comment by NeonDaniel** [comment]
this skill should be replaced with https://github.com/NeonGeckoCom/skill-audio-recording

**Comment by NeonDaniel** [comment]
I don't believe this applies to `skill-audio-recording`, but if it does then please open a new issue in that repository
